
CREATE DATABASE IF NOT EXISTS `cursos` DEFAULT CHARACTER SET latin1 COLLATE utf8_general_ci;
USE `cursos`;

CREATE USER 'cursosuser'@'%' IDENTIFIED BY 'cursospass';GRANT USAGE ON *.* TO 'cursosuser'@'%' IDENTIFIED BY 'cursospass' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `cursos`.* TO 'cursosuser'@'%';
